### ISSUE TITLE
How can we explicitly call layout() or masonry() method in angular2 when resizing the content?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [jelgblad/angular2-masonry-demo#1]
Actually Masonry method is automatically called when one resize the browser.But my issue is when I change the other content of dom, the masonry method is not called.I want to explicitly call this method how?

**Comment by jelgblad** [comment]
https://github.com/jelgblad/angular2-masonry/issues/10#issuecomment-243238801

**Comment by sudhirroy-tudip** [comment]
Thanks for support @jelgblad  but what I want to get is still unclear.Let me explain you my problem..
<masonry>
<masonry-brick></masonry-brick>
</masonry>

I have a button on which click event is set like showMore so when I click that button I want to call layout method like

public showMore(){

..........  .layout();     //In space of ..... what should i write...
}
Please Clear me..

**Comment by jelgblad** [comment]
Hey,
I would probably do something like this:

``` html
<!-- create template reference variable myMasonry -->
<masonry #myMasonry>
    <masonry-brick *ngFor="let item of items">
        <h3>{{item.title}}</h3>

        <!-- pass template reference to function -->
        <button (click)="showMore(myMasonry, item)">Show more</button>

        <div *ngIf="item.expanded">
            More text!
        </div>
    </masonry-brick>
</masonry>
```

``` javascript
showMore(masonry: AngularMasonry, item) {
    item.expanded = !item.expanded;
    // tell masonry to layout items
    masonry.layout();
}
```
